---
title: "从数据到论文"
author: "姓名"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo         = FALSE,
    warning      = FALSE, 
    message      = FALSE,
    fig.width    = 5, 
    fig.asp      = 0.618,
    dpi          = 600,
    fig.showtext = TRUE
)
options(digits = 3)
```


我们的课程目标：用R语言生成一份完整的word分析报告，内容包括读取数据，画出图形以及建立模型。



# 数据

```{r}
library(tidyverse)

rawdat <- haven::read_sav("../data/Study 4/Study 4.sav")
sjPlot::view_df(rawdat)
```


```{r}
d <- rawdat %>% 
  rowwise() %>% 
  transmute(
    Mnos           = Mnos,
    Nostalgia      = mean(c_across(starts_with("NOS"))),
    Skepticism     = mean(c_across(starts_with("SKEP"))),
    Social_connect = mean(c_across(starts_with("SCN"))),
    Support_robot  = mean(c_across(starts_with("SUPPORT"))),
    Adoption_robot =  sum(c_across(starts_with("ADOPT"))),
  ) %>% 
  ungroup() 

d %>% 
  head() %>% 
  flextable::flextable()
```




# Procedure and Materials

```{r}
constructs <- c("NOS", "SCN", "SKEP", "SUPPORT")
constructs %>%
  set_names() %>%
  map(
    ~ rawdat %>%
      summarise(
        alpha = performance::cronbachs_alpha(pick(starts_with(.x)))
      )
  ) %>%
  list_rbind(names_to = "term")
```




# Results and Discussion
```{r}
ta <- d %>% 
  group_by(Mnos) %>% 
  rstatix::get_summary_stats() %>% 
  select(variable, Mnos, mean, sd) %>% 
  arrange(variable, Mnos)
ta
```



```{r}
tb <- c(
  "Nostalgia",
  "Skepticism",
  "Social_connect",
  "Support_robot",
  "Adoption_robot"
) %>%
  set_names() %>%
  map(~ as.formula(paste(.x, "~ Mnos"))) %>%
  map(
    ~ d %>%
      rstatix::anova_test(.x) %>%
      as_tibble()
  ) %>%
  list_rbind(names_to = "variable")
tb
```


```{r}
ta %>% 
  full_join(mutate(tb, Mnos = 0), by = join_by(variable, Mnos)) %>% 
  flextable::flextable() %>% 
  flextable::set_formatter(p = function(x) {
    if_else(is.na(x), "", formatC(x, format = "e", digits = 2))
  }) %>% 
  flextable::hline(i = c(2,4,6,8)) %>% 
  flextable::autofit()
```




# Mediation Analyses(table 6)

## using traditional way

```{r}
d_corr <- d %>% 
  select(Mnos, Social_connect, Skepticism, Support_robot, Adoption_robot) %>% 
  cor()

d_corr[lower.tri(d_corr)] <- NA

d_corr <- d_corr %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "Variables")
```


```{r}
d %>% 
  select(Mnos, Social_connect, Skepticism, Support_robot, Adoption_robot) %>% 
  summarise(
    across(everything(), list(Mean = mean, Std.Dev = sd))
  ) %>% 
  pivot_longer(
    cols          = everything(),
    names_to      = c("Variables", ".value"),
    names_pattern = "(.*)_(Mean|Std.Dev)"
  )  %>% 
  left_join(
    d_corr,
    by = join_by(Variables)
  ) %>% 
  flextable::flextable() %>% 
  flextable::autofit()
```


## using rstatix

```{r}
library(rstatix)

d_corr <- d %>% 
  select(-Nostalgia) %>% 
  rstatix::cor_mat() %>% 
  rstatix::pull_upper_triangle()
d_corr

# or
# d %>% 
#   rstatix::cor_mat() %>% 
#   replace_upper_triangle(by = "-")
```


```{r}
d %>% 
  select(-Nostalgia) %>% 
  rstatix::get_summary_stats() %>% 
  select(variable, mean, sd) %>% 
  left_join(
    d_corr,
    by = join_by(variable == rowname)
  ) %>% 
  flextable::flextable() %>% 
  flextable::autofit()
```





# Support for Research on Companion Robots. (Figure 5a)

## using lavaan
```{r}
library(lavaan)

model <- '

  Social_connect ~ a1 * Mnos
  Skepticism     ~ a2 * Mnos

  Support_robot  ~ cprime * Mnos + b1 * Social_connect + b2 * Skepticism
  
  # define parameters
  indirect_a := a1 * b1
  indirect_b := a2 * b2
  indirect := a1 * b1 + a2 * b2
 

'


fit <- sem(model, 
           data      = d, 
           estimator = "MLR", 
           mimic     = "Mplus")
```



```{r}
tbl_orders <- c("a1", "b1", "a2", "b2", 
                "a1b1", "a2b2", "cprime", "indirect_effect")


fit %>% 
  parameterestimates(standardized = T) %>%  
  filter(op %in% c("~", ":="))  %>% 
  select(label, est, se, pvalue, ci.lower, ci.upper, std.all) %>% 
  arrange(factor(label, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = c("est", "std.all"), color = "red") %>%
  flextable::autofit()
```




## using brms

```{r}
library(brms)

mod <- brm(
  bf(Social_connect ~ Mnos) +
    bf(Skepticism ~ Mnos) +
    bf(Support_robot ~ Mnos + Social_connect + Skepticism) +
    set_rescor(FALSE),
  family = gaussian,
  data   = d,
  chains = 4,
  cores  = 4
)
```



```{r}
print(mod, digits = 3)

fixef(mod)
```


```{r}
draws <- as_draws_df(mod)

tbl_orders <- c("a1", "b1", "a2", "b2", 
                "a1b1", "a2b2", "cprime", "indirect_effect")

draws %>% 
  transmute(
    a1     = b_Socialconnect_Mnos,
    a2     = b_Skepticism_Mnos,
    cprime = b_Supportrobot_Mnos,
    b1     = b_Supportrobot_Social_connect,
    b2     = b_Supportrobot_Skepticism
  ) %>% 
  mutate(
    a1b1            = a1 * b1,
    a2b2            = a2 * b2,
    indirect_effect = a1 * b1 + a2 * b2
  ) %>% 
  pivot_longer(
    cols          = everything(),
    names_to      = "item",
    values_to     = "value"
  ) %>% 
  group_by(item) %>% 
  ggdist::mean_hdi(.width = .95) %>% 
  arrange(factor(item, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::line_spacing(space = 0.7) %>% 
  flextable::color(j = "value", color = "red") %>% 
  flextable::autofit()
```



```{r, fig.width = 10, fig.asp= 0.45}
library(ggdist)
draws %>% 
  transmute(
    a1     = b_Socialconnect_Mnos,
    a2     = b_Skepticism_Mnos,
    cprime = b_Supportrobot_Mnos,
    b1     = b_Supportrobot_Social_connect,
    b2     = b_Supportrobot_Skepticism
  ) %>% 
  mutate(
    a1b1            = a1 * b1,
    a2b2            = a2 * b2,
    indirect_effect = a1 * b1 + a2 * b2
  ) %>% 
  pivot_longer(
    cols          = everything(),
    names_to      = "item",
    values_to     = "value"
  ) %>% 
  
  ggplot(aes(x = value)) +
  geom_vline(xintercept = 0, color = "grey50", linetype = 2) +
  geom_histogram(binwidth = .025, boundary = 0, 
                 color = "white", fill = "skyblue3", size = 1/4) +
  ggdist::stat_pointinterval(
    aes(y = 0), 
    point_interval = mode_hdi, .width = .95
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab("posterior") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(color = "transparent", fill = "transparent")
  ) +
  facet_wrap(vars(factor(item, levels = tbl_orders)), nrow = 2)
```




## brms 数据标准化之后

```{r}
standardize <- function(x) {
  (x - mean(x)) / sd(x)
}

d_s <- d %>% 
  mutate(across(everything(), standardize))

mod_s <- update(mod, newdata = d_s)
```




```{r}
draws <- as_draws_df(mod_s)

tbl_orders <- c("a1", "b1", "a2", "b2", 
                "a1b1", "a2b2", "cprime", "indirect_effect")

draws %>% 
  transmute(
    a1     = b_Socialconnect_Mnos,
    a2     = b_Skepticism_Mnos,
    cprime = b_Supportrobot_Mnos,
    b1     = b_Supportrobot_Social_connect,
    b2     = b_Supportrobot_Skepticism
  ) %>% 
  mutate(
    a1b1            = a1 * b1,
    a2b2            = a2 * b2,
    indirect_effect = a1 * b1 + a2 * b2
  ) %>% 
  pivot_longer(
    cols          = everything(),
    names_to      = "item",
    values_to     = "value"
  ) %>% 
  group_by(item) %>% 
  ggdist::mean_hdi(.width = .95) %>% 
  arrange(factor(item, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 3) %>% 
  flextable::line_spacing(space = 0.7) %>% 
  flextable::color(j = "value", color = "red") %>% 
  flextable::autofit()
```

## 对比
```{r, fig.width = 8, fig.asp= 0.4, echo=FALSE}
 p1 <- fit %>%
   standardizedSolution(type = "std.all") %>%
   filter(op %in% c("~", ":=")) %>%
   filter(label %in% c("a1", "a2")) %>%
   ggplot(aes(x = est.std, y = label)) +
   geom_pointrange(aes(xmin = ci.lower, xmax = ci.upper)) +
   scale_x_continuous(limits = c(0, 0.6)) +
   labs(x = NULL, y = NULL, title = "Frequentist using lavaan") +
   theme_bw(base_size = 16)


 p2 <- draws %>%
   transmute(
     a1   = b_Socialconnect_Mnos,
     a2   = b_Skepticism_Mnos
   ) %>%
   pivot_longer(
     cols        = everything(),
     names_to    = "item",
     values_to   = "value"
   ) %>%
   ggplot(aes(x = value, y = item)) +
   ggdist::stat_halfeye(fill = "skyblue3") +
   labs(x = NULL, y = NULL, title = "Bayesian using brms") +
   theme_bw(base_size = 16)


 library(cowplot)
 plot_grid(p1, p2, align = "hv", axis = "tblr")
```



## using blavaan
```{r}
library(lavaan)
library(blavaan)

model <- '

  Social_connect ~ a1 * Mnos
  Skepticism     ~ a2 * Mnos

  Support_robot  ~ cprime * Mnos + b1 * Social_connect + b2 * Skepticism
  
  # define parameters
  indirect_a := a1 * b1
  indirect_b := a2 * b2
  indirect   := a1 * b1 + a2 * b2
 

'


fit <- bsem(model, 
            data      = d, 
            estimator = "MLR", 
            mimic     = "Mplus")
```



```{r}
tbl_orders <- c("a1", "b1", "a2", "b2", 
                "a1b1", "a2b2", "cprime", "indirect_effect")


fit %>% 
  lavaan::parameterestimates(standardized = T) %>%  
  filter(op %in% c("~", ":=")) %>% 
  select(label, est, std.all) %>% 
  arrange(factor(label, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = c("est", "std.all"), color = "red") %>%
  flextable::autofit()
```




# Adoption of Companion Robots (Figure 5b)

```{r}
library(lavaan)

model <- '

  Social_connect  ~ a1 * Mnos
  Skepticism      ~ a2 * Mnos

  Adoption_robot  ~ cprime * Mnos + b1 * Social_connect + b2 * Skepticism
  
  # define parameters
  indirect_a := a1 * b1
  indirect_b := a2 * b2
  indirect := a1 * b1 + a2 * b2

'


fit <- sem(model, 
           data      = d, 
           estimator = "MLR", 
           mimic     = "Mplus")
```



```{r}
tbl_orders <- c("a1", "b1", "a2", "b2", 
                "a1b1", "a2b2", "cprime", "indirect_effect")


fit %>% 
  parameterestimates(standardized = T) %>%  
  filter(op %in% c("~", ":="))  %>% 
  select(label, est, se, pvalue, ci.lower, ci.upper, std.all) %>% 
  arrange(factor(label, levels = tbl_orders)) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = c("est", "std.all"), color = "red") %>% 
  flextable::autofit()
```

