---
title: "从数据到论文"
author: "姓名"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo         = FALSE,
    warning      = FALSE, 
    message      = FALSE,
    fig.width    = 5, 
    fig.asp      = 0.618,
    dpi          = 600,
    fig.showtext = TRUE
)
options(digits = 3)
```


我们的课程目标：用R语言生成一份完整的word分析报告，内容包括读取数据，画出图形以及建立模型。



# 数据

```{r}
library(tidyverse)

rawdat <- haven::read_sav("../data/Study 3/Study 3.sav")  
  
sjPlot::view_df(rawdat)
```

# Participants
```{r}
rawdat %>% count(sex)

rawdat %>% 
  summarise(
    mean = mean(age),
    sd = sd(age)
  )
```


# Procedure and Materials

```{r}
constructs <- c("nos", "con", "skep", "Support_AI", "Support_5G")
constructs %>%
  set_names() %>%
  map(
    ~ rawdat %>%
      summarise(
        alpha = performance::cronbachs_alpha(pick(starts_with(.x)))
      )
  ) %>%
  list_rbind(names_to = "term")
```



# Results and Discussion

```{r}
d <- rawdat %>% 
  rowwise() %>% 
  transmute(
    Mnos        = Mnos,
    Nostalgia   = mean(c_across(starts_with("nos"))),
    Connect     = mean(c_across(starts_with("con"))),
    Skepticism  = mean(c_across(starts_with("skep"))),
    Support_AI  = mean(c_across(starts_with("Support_AI"))),
    Support_5G  = mean(c_across(starts_with("Support_5G"))),
    enrolAI     = enrolAI,
    enrol5G     = enrol5G
  ) %>% 
  ungroup()

d %>% 
  head() %>% 
  flextable::flextable()
```


```{r}
d %>%
  group_by(Mnos) %>%
  summarise(
    across(c(Nostalgia, Connect, Skepticism, Support_AI, Support_5G), list(M = mean, SD = sd))
  ) %>%
  pivot_longer(
    cols          = -Mnos,
    names_to      = c("Variables", ".value"),
    names_pattern = "(.*)_(M|SD)",
    cols_vary     = "slowest"
  ) %>%
  flextable::flextable() %>%
  flextable::autofit()
```



# Mediation Analyses
Table 3

```{r}
d_c <- d %>% 
  select(-Nostalgia) %>% 
  cor()

d_c[lower.tri(d_c)] <- NA

d_c %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "Variables")
```



# Figure 3

## M1
```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  Support_AI ~ c1*Mnos + b1*Connect + d2*Skepticism
  Support_5G ~ c2*Mnos + b2*Skepticism + d1*Connect

  Connect    ~~  Skepticism
  Support_AI ~~  Support_5G

  indirect1ab  := a1*b1
  indirect1ad  := a2*d2
  indirect2ab  := a2*b2 
  indirect2ad  := a1*d1
  
  direct1      := c1
  direct2      := c2

'

fit1 <- sem(model, 
            data      = d, 
            estimator = "MLR", 
            mimic     = "Mplus")
```



```{r}
fit1 %>% 
  parameterestimates(standardized = T) %>%  
  #filter(op %in% c("~", ":="))  %>% 
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```



## M2

```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  Support_AI ~ c1*Mnos + b1*Connect + d2*Skepticism
  Support_5G ~ c2*Mnos + b2*Skepticism + b1*Connect

  Connect    ~~  Skepticism
  Support_AI ~~  Support_5G

'

fit2 <- sem(model, 
            data      = d, 
            estimator = "MLR", 
            mimic     = "Mplus")
```



```{r}
fit2 %>% 
  parameterestimates(standardized = T) %>%  
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```



## M3

```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  Support_AI ~ c1*Mnos + b1*Connect + b2*Skepticism
  Support_5G ~ c2*Mnos + b2*Skepticism + d1*Connect

  Connect    ~~  Skepticism
  Support_AI ~~  Support_5G

'

fit3 <- sem(model, 
            data      = d, 
            estimator = "MLR", 
            mimic     = "Mplus")
```



```{r}
fit3 %>% 
  parameterestimates(standardized = T) %>%  
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```


## M4

```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  Support_AI ~ c1*Mnos + b1*Connect + d2*Skepticism
  Support_5G ~ c1*Mnos + b2*Skepticism + d1*Connect

  Connect    ~~  Skepticism
  Support_AI ~~  Support_5G

'

fit4 <- sem(model, 
            data      = d, 
            estimator = "MLR", 
            mimic     = "Mplus")
```



```{r}
fit4 %>% 
  parameterestimates(standardized = T) %>%  
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```



## comparison M1, M2, M3, M4

Table 4
```{r}
library(lavaanExtra)
mylist <- lst(fit1, fit2, fit3, fit4)
mylist %>%
   map( ~cfa(.x, data = d)) %>%
   lavaanExtra::nice_fit(nice_table = TRUE) |>
   flextable::fontsize(size = 9, part = "all")  %>% 
   flextable::align(align = "center", part = "body") %>% 
   flextable::valign(valign = "center", part = "body")
```





# Figure 4

注意到这里的enrolAI和enrol5G是二元变量，因此需要这里的[技术](https://lavaan.ugent.be/tutorial/cat.html#endogenous-categorical-variables)


```{r}
d_ordered <- d %>% 
  mutate(
    across(starts_with("enrol"), ordered)
  )
d_ordered 
```


## M1
```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  enrolAI    ~ c1*Mnos + b1*Connect + d2*Skepticism
  enrol5G    ~ c2*Mnos + b2*Skepticism + d1*Connect

  Connect    ~~  Skepticism
  enrolAI    ~~  enrol5G

  indirect1ab  := a1*b1
  indirect1ad  := a2*d2
  indirect2ab  := a2*b2 
  indirect2ad  := a1*d1
  
  direct1      := c1
  direct2      := c2

'

fit1 <- sem(model, 
            data      = d_ordered, 
            estimator = "WLSMV", 
            mimic     = "Mplus")
```




```{r}
fit1 %>% 
  parameterestimates(standardized = T) %>%  
  #filter(op %in% c("~", ":="))  %>% 
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```



## M2

```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  enrolAI    ~ c1*Mnos + b1*Connect + d2*Skepticism
  enrol5G    ~ c2*Mnos + b2*Skepticism + b1*Connect

  Connect    ~~  Skepticism
  enrolAI    ~~  enrol5G

'

fit2 <- sem(model, 
            data      = d_ordered,  
            estimator = "WLSMV", 
            mimic     = "Mplus")
```



```{r}
fit2 %>% 
  parameterestimates(standardized = T) %>%  
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```

## M3

```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  enrolAI    ~ c1*Mnos + b1*Connect + b2*Skepticism
  enrol5G    ~ c2*Mnos + b2*Skepticism + d1*Connect

  Connect    ~~  Skepticism
  enrolAI    ~~  enrol5G

'

fit3 <- sem(model, 
            data      = d_ordered, 
            estimator = "WLSMV", 
            mimic     = "Mplus")
```



```{r}
fit3 %>% 
  parameterestimates(standardized = T) %>%  
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```


## M4

```{r}
library(lavaan)

model <- '

  Connect    ~ a1*Mnos
  Skepticism ~ a2*Mnos
  enrolAI    ~ c1*Mnos + b1*Connect + d2*Skepticism
  enrol5G    ~ c1*Mnos + b2*Skepticism + d1*Connect

  Connect   ~~  Skepticism
  enrolAI   ~~  enrol5G

'

fit4 <- sem(model, 
            data      = d_ordered, 
            estimator = "WLSMV", 
            mimic     = "Mplus")
```



```{r}
fit4 %>% 
  parameterestimates(standardized = T) %>%  
  select(-std.lv, -std.nox) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(digits = 4) %>% 
  flextable::color(j = "std.all", color = "red") %>% 
  flextable::autofit()
```



## comparison M1, M2, M3, M4

Table 5

```{r}
index <- c("chisq", "df", "pvalue", "rmsea", "cfi", "tli", "srmr")

mylist <- lst(fit1, fit2, fit3, fit4)

mylist %>%
   map(~fitMeasures(.x, fit.measures = index, output = "vector")) %>%
   map(~t(as.matrix(.x))) %>% 
   map(as.data.frame) %>% 
   list_rbind(names_to = "model") %>% 
   flextable::flextable() %>% 
   flextable::colformat_double(j = c("chisq", "srmr"), digits = 3) %>% 
   flextable::align(align = "center", part = "all") %>% 
   flextable::valign(valign = "center", part = "body")
```


